application: iou
version: 1
runtime: python
api_version: 1

handlers:
- url: /add
  script: main.py

- url: /edit
  script: main.py

- url: /json
  script: homepage.py

- url: /
  static_files: genfiles/iou.Frontend/Frontend.html
  upload: genfiles/iou.Frontend/Frontend.html

- url: /(.*)
  static_files: genfiles/iou.Frontend/\1
  upload: genfiles/iou.Frontend/*

