#!/bin/sh
APPDIR=`dirname $0`;
GWTDIR="/Users/$HOME/local/opt/gwt-mac-1.4.62"
java -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:$GWTDIR/gwt-user.jar:$GWTDIR/gwt-dev-mac.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" iou.Frontend;
